name: contatinhos
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.5
  http: ^0.13.4
  shared_preferences: ^2.0.6
  image_picker: ^1.1.2
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
